aiconoa_user:
    resource: "@AiconoaUserBundle/Controller/"
    type:     annotation
    prefix:   /

aiconoa_statistics:
    resource: "@AiconoaStatisticsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
