# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    stat_service_controller_white_list: []

services:
    statService:
         class: Aiconoa\StatisticsBundle\Service\StatService
         arguments: ["@doctrine"]
         calls:
            - [setControllerWhiteList, ["@=container.hasParameter('stat_service_controller_white_list') ? parameter('stat_service_controller_white_list') : parameter('stat_service_controller_default_white_list')"]]
         tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        #arguments: ["@another_service_name", "plain_value", "%parameter_name%"]